version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local-docker-storage
    volumes:
      - './data:/home/dynamodblocal/data'
    ports:
      - '8000:8000'
    command: "-jar DynamoDBLocal.jar -port 8000 -dbPath ./data -sharedDb"
